config/routes.rb
Rails.application.routes.draw do
  get 'home/top'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :line_items
  resources :carts
  resources :orders, only: [:new, :create]
  resources :orders_management, only: [:index, :edit] do
    put :confirm_payment
    put :deliver
  end
  devise_for :users
  resources :users
  resources :products do
    resources :taggings, only: [:new, :edit, :create, :update, :destroy]
  end
  resources :tags, except: :show
  root to: 'home#top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_details, dependent: :destroy
  after_commit :send_order_mail, on: :create
  has_many :products, dependent: :destroy

  include AASM
  enum status: { order_accepted: 0, paid: 1, delivered: 2 }
  aasm column: :status do
    state :order_accepted, initial: true
    state :paid
    state :delivered

    event :confirm_payment do
      transitions from: :order_accepted, to: :paid
    end

    event :deliver do
      transitions from: :paid, to: :delivered
    end
  end

  def checkout(cart)
    cart.line_items.each do |line_item|
      order_details.build(product_id: line_item.product_id, quantity: line_item.quantity, product: line_item.product)
    end
    save!
  end

  def total_price
    order_details.to_a.sum { |item| item.total_price }
  end

  def total_number
    order_details.to_a.sum { |item| item.quantity }
  end

  private

  def send_order_mail
    OrderMailer.completed_mail(self).deliver
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @cart = current_cart
    if @cart.line_items.empty?
      redirect_to products_url
      return
    end
    @order = Order.new
    render :layout => 'front'
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @cart = current_cart
    @order = Order.new(user_id: order_params[:user_id], shipping_address: order_params[:shipping_address])
    @order.checkout(@cart)

    respond_to do |format|
      @cart.destroy
      session[:cart_id] = nil
      format.html { redirect_to products_url, notice: '注文が完了しました.' }
      format.json { render :show, status: :created, location: @order }
    end
  rescue
    respond_to do |format|
      format.html { render :new }
      format.json { render json: @order.errors, status: :unprocessable_entity }
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: '注文が更新されました.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: '注文内容が削除されました.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:shipping_address, :user_id, :product_id)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_with(model: @order, url: orders_path, local: true) do |form| %>

  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <h2 class="sub-header">商品</h2>
  <ul class="list-group">
    <% cart.line_items.each do |line_item| %>
      <li class="list-group-item">
        <p>
          <strong>商品名:</strong>
          <%= line_item.product.name %>
        </p>
        <p>
          <strong>個数:</strong>
          <%= number_to_currency(line_item.quantity, precision: 0, unit: "個") %>
        </p>
        <p>
          <strong>小計金額:</strong>
          <%= number_to_currency(line_item.total_price, precision: 0, unit: "円") %>
        </p>
      </li>
    <% end %>
    <li class="list-group-item">
      <p>
        <strong>合計金額:</strong>
        <%= number_to_currency(cart.total_price, precision: 0, unit: "円") %>
      </p>
    </li>
  </ul>

  <h2 class="sub-header">お客様情報</h2>
  <ul class="list-group">
    <li class="list-group-item">
      <p>
        <strong>氏名:</strong>
        <%= current_user.name %>
      </p>
    </li>

    <li class="list-group-item">
      <p>
        <strong>メールアドレス:</strong>
        <%= current_user.email %>
      </p>
    </li>
  </ul>

  <div class="form-group">
    <%= form.label :shipping_address %>
    <%= form.text_field :shipping_address, class: "form-control" %>
  </div>

  <%= form.hidden_field :user_id, value: current_user.id %>

  <div class="actions">
    <%= form.submit '購入確定', class: "btn btn-success", data: { confirm: 'この内容で購入してもよろしいですか？ ' } %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Shipping address</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.shipping_address %></td>
        <td><%= order.user_id %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>商品購入</h1>

<%= render 'form', order: @order, cart: @cart %>

<%= link_to '戻る', products_path, class: 'btn btn-primary' %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Shipping address:</strong>
  <%= @order.shipping_address %>
</p>

<p>
  <strong>User:</strong>
  <%= @order.user_id %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>