config/routes.rb
Rails.application.routes.draw do
  get 'home/top'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :line_items
  resources :carts
  resources :orders, only: [:new, :create]
  resources :orders_management, only: [:index, :edit] do
    put :confirm_payment
    put :deliver
  end
  devise_for :users
  resources :users
  resources :products do
    resources :taggings, only: [:new, :edit, :create, :update, :destroy]
  end
  resources :tags, except: :show
  root to: 'home#top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :destroy
    has_many :products, dependent: :destroy

    def add_product(product_id)
        current_item = line_items.find_or_initialize_by(product_id: product_id)
        current_item.quantity += 1
        current_item
    end

    def total_price
        line_items.to_a.sum { |item| item.total_price }
      end

      def total_number
        line_items.to_a.sum { |item| item.quantity }
      end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    render :layout => 'front'
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'カートが作成されました' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'カートが更新されました' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = current_cart
    @cart.destroy
    session[:cart_id] = nil

    respond_to do |format|
      format.html { redirect_to products_url, notice: 'カートが削除されました' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cart_params
      params.fetch(:cart, {})
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
        <% cart.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to '詳細', cart %></td>
        <td><%= link_to '編集', edit_cart_path(cart) %></td>
        <td><%= link_to '削除', cart, method: :delete, data: { confirm: '本当に削除しますか?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

/<%= link_to '', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>

<h2 class="sub-header">カート</h2>
<table class="table-striped table">
  <thead>
    <tr>
      <th>商品名</th>
      <th>個数</th>
      <th>価格</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cart.line_items.each do |item| %>
      <tr>
        <td><%= item.product.name %></td>
        <td>&times;<%= item.quantity %></td>
        <td class="item_price"><%= number_to_currency(item.total_price) %></td>
      </tr>
    <% end %>
  </tbody>

  <tr>
    <td colspan="2">合計</td>
    <td class="total_cell"><%= number_to_currency(@cart.total_price) %></td>
  </tr>
</table>

<%= link_to '購入を続ける', products_path, class: 'btn btn-primary' %>
<%= link_to '購入する', new_order_path, class: 'btn btn-primary' %>
<%= link_to 'カートを空にする', cart_path(id: @cart.id), method: :delete, class: 'btn btn-default' %>