config/routes.rb
Rails.application.routes.draw do
  get 'home/top'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :line_items
  resources :carts
  resources :orders, only: [:new, :create]
  resources :orders_management, only: [:index, :edit] do
    put :confirm_payment
    put :deliver
  end
  devise_for :users
  resources :users
  resources :products do
    resources :taggings, only: [:new, :edit, :create, :update, :destroy]
  end
  resources :tags, except: :show
  root to: 'home#top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :line_items, dependent: :destroy
    belongs_to :cart
    belongs_to :line_item
    belongs_to :order
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    render layout: 'front'
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: '商品が登録されました' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: '商品情報が更新されました' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: '商品が削除されました' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :price, :stock, :note, :showing)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :商品名 %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :価格 %>
    <%= form.number_field :price, class: "form-control", placeholder: '半角数字'%>
  </div>

  <div class="form-group">
    <%= form.label :在庫 %>
    <%= form.number_field :stock, class: "form-control", placeholder: '半角数字'%>
  </div>

  <div class="form-group">
    <%= form.label :備考 %>
    <%= form.text_area :note, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :販売 %>する
    <%= form.check_box :showing %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h2>商品情報編集</h2>

<%= render 'form', product: @product %>

<%= link_to '詳細', @product, class: 'btn btn-link' %> |
<%= link_to '戻る', products_path, class: 'btn btn-link' %>

app/views/products/index.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <p id="notice"><%= notice %></p>
  </div>
<% end %>

<h2 class="sub-header">Products</h2>

<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>商品名</th>
        <th>価格</th>
        <th>在庫</th>
        <th>備考</th>
        <th>販売</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= product.name %></td>
          <td><%= product.price %></td>
          <td><%= product.stock %></td>
          <td><%= product.note %></td>
          <td><%= product.showing? ? '可能' : '不可' %></td>
          <td><%= link_to '詳細', product %></td>
          <% if user_signed_in? %>
            <% if current_user.admin_flg? %>
              <td><%= link_to '編集', edit_product_path(product) %></td>
              <td><%= link_to '削除', product, method: :delete, data: { confirm: '本当に削除しますか?' } %></td>
            <% else %>
              <td><%= link_to 'カートに入れる', line_items_path(product_id: product.id), method: :post, class: 'btn btn-primary' %></td>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<% if user_signed_in? %>
  <% if current_user.admin_flg? %>
    <%= link_to '新規登録', new_product_path, class: 'btn btn-primary' %>
    <% end %>
<% end %>

app/views/products/new.html.erb
<h2>商品登録</h2>

<%= render 'form', product: @product, title: '登録' %>

<%= link_to '戻る', products_path, class: 'btn btn-link' %>

app/views/products/show.html.erb
<% if notice %>
  <div class="alert alert-success alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <p id="notice"><%= notice %></p>
  </div>
<% end %>

<p>
  <strong>商品名:</strong>
  <%= @product.name %>
</p>

<ul class="list-group">
  <li class="list-group-item">
    <p>
      <strong>価格:</strong>
      <%= number_to_currency(@product.try(:price), precision: 0, unit: "円") %>
    </p>

    <p>
      <strong>在庫:</strong>
      <%= number_to_currency(@product.try(:stock), precision: 0, unit: "個") %>
    </p>

    <p>
      <strong>備考:</strong>
      <%= @product.note %>
    </p>

    <p>
      <strong>販売:</strong>
      <%= @product.showing? ? '可能' : '不可' %>
    </p>
  </li>
</ul>

<% if user_signed_in? %>
  <% if current_user.admin_flg? %>
    <%= link_to '編集', edit_product_path(@product), class: 'btn btn-link' %> |
  <% else %>
    <%= link_to 'カートに入れる', line_items_path(product_id: @product.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>
<%= link_to '戻る', products_path, class: 'btn btn-link' %> |
<% if user_signed_in? %>
  <% if current_user.admin_flg? %>
    <%= link_to '新規登録', new_product_path(@product), class: 'btn btn-link' %>
  <% end %>
<% end %>