config/routes.rb
Rails.application.routes.draw do
  get 'home/top'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :line_items
  resources :carts
  resources :orders, only: [:new, :create]
  resources :orders_management, only: [:index, :edit] do
    put :confirm_payment
    put :deliver
  end
  devise_for :users
  resources :users
  resources :products do
    resources :taggings, only: [:new, :edit, :create, :update, :destroy]
  end
  resources :tags, except: :show
  root to: 'home#top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user && user.admin_flg?
      can :access, :rails_admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :line_items, dependent: :destroy
    has_many :products, dependent: :destroy

    def add_product(product_id)
        current_item = line_items.find_or_initialize_by(product_id: product_id)
        current_item.quantity += 1
        current_item
    end

    def total_price
        line_items.to_a.sum { |item| item.total_price }
      end

      def total_number
        line_items.to_a.sum { |item| item.quantity }
      end
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
  has_many :products, dependent: :destroy

  def total_price
    product.price * quantity
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_details, dependent: :destroy
  after_commit :send_order_mail, on: :create
  has_many :products, dependent: :destroy

  include AASM
  enum status: { order_accepted: 0, paid: 1, delivered: 2 }
  aasm column: :status do
    state :order_accepted, initial: true
    state :paid
    state :delivered

    event :confirm_payment do
      transitions from: :order_accepted, to: :paid
    end

    event :deliver do
      transitions from: :paid, to: :delivered
    end
  end

  def checkout(cart)
    cart.line_items.each do |line_item|
      order_details.build(product_id: line_item.product_id, quantity: line_item.quantity, product: line_item.product)
    end
    save!
  end

  def total_price
    order_details.to_a.sum { |item| item.total_price }
  end

  def total_number
    order_details.to_a.sum { |item| item.quantity }
  end

  private

  def send_order_mail
    OrderMailer.completed_mail(self).deliver
  end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :line_items, dependent: :destroy
    belongs_to :cart
    belongs_to :line_item
    belongs_to :order
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :product
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :trackable, :validatable
  has_many :orders, dependent: :destroy

  ROLE = %w(admin general)
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    render :layout => 'front'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/taggings_helper.rb
module TaggingsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
   <head>
      <title>Eshop</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      <!-- TODO add these as assets -->
      <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
      <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
      <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
      <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
   </head>

   <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" >Eshop</a>
      <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber" aria-expanded="false" aria-label="ナビゲーションの切替">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="Navber">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to '商品', products_path %><span class="sr-only">(現位置)</span>
          </li>
          <% if user_signed_in? %>
            <% if current_user.admin_flg? %>
              <li class="nav-item">
                <%= link_to 'ユーザー', users_path %>
              </li>
              <% end %>
          <% end %>
          <li class="nav-item">
          <%= link_to '注文一覧', orders_management_index_path %>
          </li>
          <% if user_signed_in? %>
            <li class="nav-item">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
            </li>
            <% else %>
            <li class="nav-item">
            <%= link_to "ログイン", new_user_session_path, class: 'post' %>
            </li>
          <% end %>
          <li class="nav-item">
            <%= link_to "新規登録", new_user_path, class: 'post' %>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </nav>
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
      <!--Body content-->
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html2.erb
<!DOCTYPE html>
<html>
   <head>
      <title>Eshop</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      <!-- TODO add these as assets -->
      <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
      <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
      <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
      <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
   </head>

   <body>
      <div class="container-fluid">
      <%= link_to "Eshop", "/products", class: "navbar-brand" %>
         <div class="row">
            <% if notice %>
              <p class="alert alert-success"><%= notice %></p>
            <% end %>
            <% if alert %>
             <p class="alert alert-danger"><%= alert %></p>
            <% end %>
            <div class="col-sm-4 col-md-3 sidebar">
              <div class="mini-submenu">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </div>
              <% if user_signed_in? %>
                <ul class="nav nav-sidebar">
                  <li class="active"><%= link_to 'Products', products_path %></li>
                  <li class="active"><%= link_to 'Users', users_path %></li>
                  <li class="active"><%= link_to 'orders', orders_management_index_path %></li>
                </ul>
              <% end %>
            </div>
            <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
               <!--Body content-->
              <%= yield %>
            </div>
         </div>
      </div>
   </body>
</html>

app/views/layouts/front.html.erb
<!DOCTYPE html>
<html>
    <title>Eshop</title>
    <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
      <!-- TODO add these as assets -->
      <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
      <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
      <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
      <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" >Eshop</a>
      <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber" aria-expanded="false" aria-label="ナビゲーションの切替">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="Navber">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to '商品', products_path %><span class="sr-only">(現位置)</span>
          </li>
          <% if user_signed_in? %>
            <% if current_user.admin_flg? %>
              <li class="nav-item">
                <%= link_to 'ユーザー', users_path %>
              </li>
              <% end %>
          <% end %>
          <li class="nav-item">
          <%= link_to '注文一覧', orders_management_index_path %>
          </li>
          <% if user_signed_in? %>
            <li class="nav-item">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
            </li>
            <% else %>
            <li class="nav-item">
            <%= link_to "ログイン", new_user_session_path, class: 'post' %>
            </li>
          <% end %>
          <li class="nav-item">
            <%= link_to "新規登録", new_user_path, class: 'post' %>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </nav>

      <div class="jumbotron">
        <h1>EShop</h1>
        <p class="lead">Ehoptest</p>
        <p class="lead">test</p>
      </div>

      <%= yield %>

    </div> <!-- /container -->
   </body>
</html>